In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Numy merupakan library python digunakan untuk komputasi matriks
Matplotlib merupakan library python untuk presentasi data berupa grafik atau plot.

In [ ]:
dataset = pd.read_csv('Data.csv - Sheet1.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(x)

[['Korea' 37.0 77000.0]
 ['Jepang' 26.0 48000.0]
 ['Australia' 39.0 55000.0]
 ['Jepang' 25.0 68000.0]
 ['Australia' 40.0 nan]
 ['Korea' 32.0 87000.0]
 ['Jepang' nan 75000.0]
 ['Korea' 27.0 79000.0]
 ['Australia' 50.0 83000.0]
 ['Korea' 25.0 67000.0]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] =imputer.transform(x[:, 1:3])


In [ ]:
print(x)

[['Korea' 37.0 77000.0]
 ['Jepang' 26.0 48000.0]
 ['Australia' 39.0 55000.0]
 ['Jepang' 25.0 68000.0]
 ['Australia' 40.0 71000.0]
 ['Korea' 32.0 87000.0]
 ['Jepang' 33.44444444444444 75000.0]
 ['Korea' 27.0 79000.0]
 ['Australia' 50.0 83000.0]
 ['Korea' 25.0 67000.0]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[0.0 0.0 1.0 37.0 77000.0]
 [0.0 1.0 0.0 26.0 48000.0]
 [1.0 0.0 0.0 39.0 55000.0]
 [0.0 1.0 0.0 25.0 68000.0]
 [1.0 0.0 0.0 40.0 71000.0]
 [0.0 0.0 1.0 32.0 87000.0]
 [0.0 1.0 0.0 33.44444444444444 75000.0]
 [0.0 0.0 1.0 27.0 79000.0]
 [1.0 0.0 0.0 50.0 83000.0]
 [0.0 0.0 1.0 25.0 67000.0]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=1)

In [ ]:
print(x_train)

[[0.0 1.0 0.0 33.44444444444444 75000.0]
 [1.0 0.0 0.0 40.0 71000.0]
 [0.0 0.0 1.0 37.0 77000.0]
 [0.0 1.0 0.0 25.0 68000.0]
 [0.0 1.0 0.0 26.0 48000.0]
 [0.0 0.0 1.0 27.0 79000.0]
 [1.0 0.0 0.0 50.0 83000.0]
 [0.0 0.0 1.0 32.0 87000.0]]


In [ ]:
print(x_test)

[[1.0 0.0 0.0 39.0 55000.0]
 [0.0 0.0 1.0 25.0 67000.0]]


In [ ]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
print(y_test)

[0 1]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:,3:] = sc.fit_transform(x_train[:,3:])
x_test[:,3:] = sc.transform(x_test[:,3:])

In [ ]:
print(x_train)

[[0.0 1.0 0.0 -0.04572280715031381 0.1338965528032355]
 [1.0 0.0 0.0 0.7843219995784568 -0.22316092133872592]
 [0.0 0.0 1.0 0.4044709863296975 0.31242528987421625]
 [0.0 1.0 0.0 -1.11493306666534 -0.49095402694519696]
 [0.0 1.0 0.0 -0.9883160622490869 -2.276241397655004]
 [0.0 0.0 1.0 -0.8616990578328337 0.49095402694519696]
 [1.0 0.0 0.0 2.0504920437409884 0.8480115010871583]
 [0.0 0.0 1.0 -0.22861403575156813 1.20506897522912]]


In [ ]:
print(x_test)

[[1.0 0.0 0.0 39.0 55000.0]
 [0.0 0.0 1.0 25.0 67000.0]]
